-- =====================================================
-- OTP Codes table — for email OTP via Gmail SMTP
-- =====================================================
-- Stores OTP codes generated by the send-otp Edge Function.
-- The verify-otp Edge Function checks and marks them used.
-- =====================================================

CREATE TABLE IF NOT EXISTS public.otp_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL,
  code_hash TEXT NOT NULL,
  purpose TEXT NOT NULL DEFAULT 'password_reset',
  attempts INTEGER NOT NULL DEFAULT 0,
  verified BOOLEAN NOT NULL DEFAULT false,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for fast lookup by email + purpose
CREATE INDEX IF NOT EXISTS idx_otp_codes_email_purpose
  ON public.otp_codes (email, purpose, created_at DESC);

-- Enable RLS — we will NOT create permissive policies here on purpose.
-- The otp_codes table should only be read/written by the service role
-- (the Edge Functions), never by the anon/authenticated roles from the
-- browser. So we enable RLS and add NO policies, which means the public
-- role (anon) gets zero access. The service_role bypasses RLS.
ALTER TABLE public.otp_codes ENABLE ROW LEVEL SECURITY;

-- Clean up old OTP rows periodically (optional helper function).
-- We also delete expired/used rows before inserting a new OTP in the
-- Edge Function, so this is just a safety net.
CREATE OR REPLACE FUNCTION public.cleanup_old_otp_codes()
RETURNS void
LANGUAGE sql
SECURITY DEFINER
AS $$
  DELETE FROM public.otp_codes
  WHERE expires_at < now() - interval '1 hour'
     OR (verified = true AND created_at < now() - interval '1 hour');
$$;
